{% set name = "ExpressBetaDiversity" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dparks1134/ExpressBetaDiversity/archive/v{{ version }}.tar.gz
  sha256: 4dbdbcfc6aad72b0890f348877d6e096ead0ed4d5c2515904eb591a694b215c3

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  run:
    - python >=3.6
    - numpy
    - matplotlib-base

test:
  commands:
    - ExpressBetaDiversity -u | grep -F 'Passed all unit tests.'
    - ExpressBetaDiversity -h
    - convertToEBD.py -h
    - convertToFullMatrix.py -h

about:
  home: https://github.com/dparks1134/ExpressBetaDiversity
  license: GPL-3
  license_family: GPL3
  license_file: license.txt
  summary: 'Taxon- and phylogenetic-based beta diversity measures.'

  description: 'Taxon- and phylogenetic-based beta diversity measures.'
  doc_url: https://github.com/dparks1134/ExpressBetaDiversity
  dev_url: https://github.com/dparks1134/ExpressBetaDiversity

extra:
  recipe-maintainers:
    - aaronmussig
  identifiers:
    - doi:10.1038/ismej.2012.88
