{% set name = "ExpressBetaDiversity" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dparks1134/ExpressBetaDiversity/archive/v{{ version }}.tar.gz
  sha256: 2d333af3da5c0656c5dfdf8ab4423da7c08d9dcd273def5100878012959733c7

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  run:
    - python =2.7
    - numpy
    - matplotlib-base

test:
  commands:
    - ExpressBetaDiversity -u | grep -F 'Passed all unit tests.'
    - ExpressBetaDiversity -h
    - convertToEBD.py -h
    - convertToFullMatrix.py -h

about:
  home: https://github.com/dparks1134/ExpressBetaDiversity
  license: GPL-3
  license_family: GPL3
  license_file: license.txt
  summary: 'Taxon- and phylogenetic-based beta diversity measures.'

  description: 'Taxon- and phylogenetic-based beta diversity measures.'
  doc_url: https://github.com/dparks1134/ExpressBetaDiversity
  dev_url: https://github.com/dparks1134/ExpressBetaDiversity

extra:
  recipe-maintainers:
    - aaronmussig
  identifiers:
    - doi:10.1038/ismej.2012.88
